### ISSUE TITLE
Volume Slider Starts In Wrong Position

### ISSUE THREAD

**Issue by NiteKat** [bmnielsen/openbw-replay-viewer#1]
I opened the replay viewer by following the link https://bmnielsen.github.io/openbw-replay-viewer/?rep=https://sail.krasi0.com/uploadedReplays/85461679390942.bin and noticed that sound was playing, however the volume bar starts at the bottom (muted). I can't quite get a screenshot, because when I hit the keyboard shortcut to take a screenshot the replay viewer recognizes the position of the slider and then mutes the audio until I move it. Actually, just noticed if I hit the keyboard shortcut to take a screenshot even with the slider not up, it mutes after initial load.

![image](https://github.com/user-attachments/assets/95aab10f-54eb-4073-b17a-616abcfbd1f3)

**Comment by bmnielsen** [comment]
Should be fixed now
